import { container } from "tsyringe";
import "@shared/infra/container/provider/index";
import { UserService } from "@modules/Users/service/user.service";
import { IAuth, User } from "@modules/Users/dto/services.dto";
import { Company } from "@modules/company/dto/company.dto";
import { CompanyService } from "@modules/company/service/company.service";
import { Keys } from "@modules/Keys/dto/keys.dto";
import { KeysService } from "@modules/Keys/service/keys.service";
import { Plans } from "@modules/plans/dto/plans.dto";
import { PlansService } from "@modules/plans/service/plans.service";
import { Limit } from "@modules/limit/dto/limit.dto";
import { LimitService } from "@modules/limit/service/limit.service";
import { Authorization } from "@shared/authorization";
import { JwtService } from "@shared/services/jwtService/jwtService.service";
import { Auth } from "@modules/Users/service/auth.service";
import { ProductService } from "@modules/product/service/product.service";
import { SalesDto } from "@modules/sales/dto/sales.dto";
import { SalesServices } from "@modules/sales/service/sales.service";
import { ICategories } from "../../../modules/categories/dto/categories.dto";
import { CategoriesServices } from "@modules/categories/service/categories.service";
import { Can } from "@shared/authorization/can";
import { EmployeesServices } from "@modules/employees/service/employees.service";
import { IKafkaProducer, Producers } from "./provider/kafka/producer/kafka-producer";
import { TokenService } from "@modules/token/service/token.service";
import { AuthEmployees } from "@modules/employees/service/employees.auth.service";

container.register<IAuth>("auth", Auth);
container.registerSingleton<User>("userService", UserService);
container.registerSingleton("authorization", Authorization);
container.registerSingleton("jwtService", JwtService);
container.registerSingleton<Company>("companyService", CompanyService);
container.register<Keys>("keysService", KeysService);
container.register<Plans>("plansService", PlansService);
container.register<Limit>("limitService", LimitService);
container.registerSingleton("productService", ProductService);
container.register<SalesDto>("salesService", SalesServices);
container.register<ICategories>("categoriesService", CategoriesServices);
container.registerSingleton("employeesService", EmployeesServices);
container.registerSingleton<IKafkaProducer>("KafkaProducer", Producers);
container.registerSingleton("can", Can);
container.register('tokenService', TokenService)
container.register('authEmployees', AuthEmployees)